integracion sin pasar los tests

diff --git a/.github/workflows/dev_iyc-taller.yml b/.github/workflows/dev_iyc-taller.yml
--- a/.github/workflows/dev_iyc-taller.yml
+++ b/.github/workflows/dev_iyc-taller.yml
@@ -40,9 +40,12 @@ jobs:
       - name: Extract failed tests
         id: extract-failures
         run: |
-          FAILED=$(awk '/short test summary info/{flag=1; next} /=+/{flag=0} flag' result.log | grep FAILED || echo "No failed tests")
+          echo "Running extract..."
+          FAILURES=$(pytest -v 2>&1 | awk '/short test summary info/{flag=1; next} /={3,}/{flag=0} flag' | grep FAILED || echo "No failed tests")
+          echo "Output:"
+          echo "$FAILURES"
           echo "failure<<EOF" >> $GITHUB_OUTPUT
-          echo "$FAILED" >> $GITHUB_OUTPUT
+          echo "$FAILURES" >> $GITHUB_OUTPUT
           echo "EOF" >> $GITHUB_OUTPUT
 
   scan:
